  name: NPM Web App CI
  
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'
            
        - name: Setup JFrog
          uses: jfrog/setup-jfrog@v1
          with:
           subdomain: acme
           
        - name: Install dependencies
          run: npm ci
  
        - name: Run tests
          run: npm test
  
        - name: Build application
          run: npm run build
  
        - name: publish npm package
          run: npm publish
